# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ee7ebb3b599758076cac3d56b953e0bb74393193114eb0698b2fb3891c6091eec327487a4aaeed8421d1245a3e1e807e8293e6f8e9d8aa718b5e1a04c46f1ee

test:
  secret_key_base: 00ffe56d82f8fb22802794dcf688f37f5137000ffd048805f648262dd4ab5618d59748ec7127c6f42788ba0fd4881db753e29606c7685981595b81e111d206a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
